---
name: Build and Deploy React App to CloudFront
on:
  push: 
      branches: [main]
jobs: 
  build-and-deploy: 
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      BUCKET: react-buckets
      DIST: build
      REGION: ap-northeast-1
      DIST_ID: E1G11EQSM1M7BH

    steps:
    # Clone the github repository
    - name: Checkout
      uses: actions/checkout@v2

    # install aws cli and configure credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.REGION }}

    #- name: Use Node.js ${{ matrix.node-version }}
    #  uses: actions/setup-node@v2
    # with:
    #   node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: |
        node --version
        yarn add ci --production

    - name: Build Static Website
      run: yarn run build

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"